retain_result: models/qwen-vl-3b/ft_retain90+tofu/eval_results/eval_log_aggregated.json
# orig llama
# models/llama2-7b-chat/eval_results/eval_log_aggregated.json
# tofu llama 
# models/llama2-7b-tofu/eval_results/eval_log_aggregated.json
# ckpt_result: models/llama2-7b/ft_full_epoch5_lr1e-05__wd0.01_lora/idk__beta1.0_lr1e-05_forget10_5_L10.0_L00.0/checkpoint-500/eval_results/eval_log_aggregated.json
ckpt_result:   models/qwen-vl-3b/ft_full+tofu/eval_results/eval_log_aggregated.json
method_name: retain90
submitted_by: ztan
save_file: /home/cxu-serve/p62/ztan12/multimodal_unlearning/models/qwen-vl-3b/ft_retain90+tofu/eval_results/retain90_vs_full.csv
