model_path: /home/cxu-serve/p62/ztan12/multimodal_unlearning/models/qwen-vl-3b/finetuned/ft_full+tofu/batch_size1_lr1e-05
processor_path: /home/cxu-serve/p62/ztan12/multimodal_unlearning/models/qwen-vl-3b/finetuned/ft_full+tofu/batch_size1_lr1e-05
model_family: qwen-vl-3b
save_dir: ${model_path}/eval_results/

#dataset path for each of the datasets to be evaluated
data_path: [therem/faces_v1, therem/faces_v1, therem/faces_v1, therem/faces_v1, therem/faces_v1, therem/faces_v1]
split: forget10_perturbed
split_list:
  - real_faces
  - real_world
  - ${split}
  - retain_perturbed
  - ${split}
  - retain_perturbed


question_key: [question, question, question, question, question, question]
question_strategy: [random_faces, column, random_caption, random_caption, random_faces, random_faces ]
answer_key: [answer, answer, caption, caption, name, name]

base_answer_key: [answer, answer, paraphrased_caption, paraphrased_caption, name, name]
perturbed_answer_key: [options, options, perturbed_captions, perturbed_captions, perturbed_names, perturbed_names]

eval_task: [eval_real_faces_wo_options , eval_real_world_wo_options, eval_log_forget, eval_log, eval_forget_facerec, eval_retain_facerec]

# ids of the tasks to be evaluated, like [0, 1, 2], set to None to evaluate all tasks
eval_task_ids: None

# max length of the input text (including image tokens)
max_length: 128
generation:
  max_new_tokens: 32

save_generated_text: true

#
ds_size: 50

overwrite: true

batch_size: 1
reinitialize_weights: false
retain_result: null

