model_family: qwen-vl-3b
model_path: /home/cxu-serve/p62/ztan12/multimodal_unlearning/models/qwen-vl-3b/ft_full+tofu
LoRA:
  r: 0
  alpha: 32
  dropout: 0.00

lr: 1e-5
forget_data_path: therem/faces_v1
retain_data_path: therem/faces_v1

forget_split: forget10+tofu
retain_split: retain90+tofu
batch_size: 2
gradient_accumulation_steps: 4
num_epochs: 5
# available losses 
# retain_ft - finetune on retain
# grad_ascent - maximize loss on forget
# grad_diff_forget_ce_retain_ce  - loss on retain  minus loss on forget (cross entropy both)
# grad_diff_forget_entropy_retain_ce - crossentropy (CE) on retain minus entropy on forget
# grad_diff_forget_entropy_retain_KL - KL on retain minus entropy on forget
# grad_diff_forget_ce_retain_KL -  KL between original and current model on retain minus loss on forget
# grad_diff_forget_KL_retain_KL - KL between original and current model on retain minus KL between original and current model on forget
# grad_diff_forget_KL_retain_CE - crossentropy on retain minus KL between original and current model on forget
# KL - forget CE loss + KL divergence between old model and current on retain
# idk - finetune on pairs (forget, i dont know)
# dpo - modified dpo loss 
# npo - negative preference optimization
# scrub - teacher-student training, KL(teacher, student) + KL(student, teacher)
# eco - corrupt prompt on the forget set with pretrained token and promptclassifier
# eco_ft - pretrain on corrupted prompts from eco
# LLMU - 
# RMU - Representation Misdirection for Unlearning 
# influence - 
# multi delete

forget_loss: dpo
# max_grad_norm: 
loss_beta: 1.0
# calculate l1\l0 norm from zero, or from the initial model
# zero\init
l_norm_from: zero
# l1 and l0 regularization weights
l1_lambda: 0.0
l0_lambda: 0.0
max_length: 2048

save_dir: ${model_path}/${forget_loss}_${forget_split}_L1_${l1_lambda}_from${l_norm_from}
# save_dir: ${model_path}/RMU_init_0.01
overwrite_dir: true
weight_decay: 0.01
eval_while_train: false
save_ckpts: false
save_model: true
seed: 42
freeze_vision_module: "true"